# DICTIONARY

In [16]:
#format

dict={
    "key" : "value"
}
print(dict)

{'key': 'value'}


In [4]:
#eg

info={
    "name":"Subham Nayak",
    "age":21,
    "marks":[23,21,5,15],
    "weight":73.5,
    "male":True
}
print(info)


{'name': 'Subham Nayak', 'age': 21, 'marks': [23, 21, 5, 15], 'weight': 73.5, 'male': True}


In [6]:
#type

print(type(info))

<class 'dict'>


In [5]:
#access

print(info["name"])

Subham Nayak


In [7]:
print(info["marks"])

[23, 21, 5, 15]


In [8]:
print(info[height]) #error

NameError: name 'height' is not defined

In [9]:
#mutable

info["age"]=30
print(info)

{'name': 'Subham Nayak', 'age': 30, 'marks': [23, 21, 5, 15], 'weight': 73.5, 'male': True}


In [10]:
info["weight"]=80
print(info)

{'name': 'Subham Nayak', 'age': 30, 'marks': [23, 21, 5, 15], 'weight': 80, 'male': True}


In [12]:
#add new key

info["contact"] = 9432373828
print(info)

{'name': 'Subham Nayak', 'age': 30, 'marks': [23, 21, 5, 15], 'weight': 80, 'male': True, 'contact': 9432373828}


In [15]:
#null

dict={}
print(dict)
dict["name"]="Kiran"
print(dict)

{}
{'name': 'Kiran'}


### nested dict.

In [19]:
student={
    "name" : "Subham",
    "subj" : {
            "phy":45,
            "chem":34,
            "math":23
        } ,
    "age" : 21
}

print(student)

{'name': 'Subham', 'subj': {'phy': 45, 'chem': 34, 'math': 23}, 'age': 21}


In [20]:
print(student["subj"])

{'phy': 45, 'chem': 34, 'math': 23}


In [22]:
print(student["subj"]["math"])

23


### Methods

In [24]:
#keys()

info1={
    "name":"Subham Nayak",
    "age":21,
    "marks":[23,21,5,15],
    "weight":73.5,
    "male":True
}

print(info1.keys())

dict_keys(['name', 'age', 'marks', 'weight', 'male'])


In [27]:
print(list(info1.keys()))  # converted to list

['name', 'age', 'marks', 'weight', 'male']


In [28]:
print(len(list(info1.keys())))

5


In [29]:
# values()

print(info1.values())

dict_values(['Subham Nayak', 21, [23, 21, 5, 15], 73.5, True])


In [30]:
#items

print(info1.items())

dict_items([('name', 'Subham Nayak'), ('age', 21), ('marks', [23, 21, 5, 15]), ('weight', 73.5), ('male', True)])


In [32]:
print(list(info1.items()))  #converted to list

[('name', 'Subham Nayak'), ('age', 21), ('marks', [23, 21, 5, 15]), ('weight', 73.5), ('male', True)]


In [33]:
pairs=list(info1.items())
print(pairs[0])

('name', 'Subham Nayak')


In [34]:
# get("key")

info1={
    "name":"Subham Nayak",
    "age":21,
    "marks":[23,21,5,15],
    "weight":73.5,
    "male":True
}
print(info1.get("marks"))

[23, 21, 5, 15]


In [36]:
# update(new_dict)

info1={
    "name":"Subham Nayak",
    "age":21,
    "marks":[23,21,5,15],
    "weight":73.5,
    "male":True
}
new_info = {"name" : "kiran nayak",
            "age" : 20
           }
info1.update(new_info)
print(info1)

{'name': 'kiran nayak', 'age': 20, 'marks': [23, 21, 5, 15], 'weight': 73.5, 'male': True}


In [1]:

cubes = {x: x**3 for x in range(1, 6)}
print(cubes)


{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}


In [3]:
nums = [10, 3, 7, 1, 9, 4, 2, 8, 5, 6]
squares = (x**2 for x in nums if x % 2 != 0)

print(squares)

<generator object <genexpr> at 0x000001755E6ED220>


In [8]:
import numpy as np

# Arrays
a = np.ones((2, 3))
b = np.zeros((3, 3))
c = np.full((2, 5),7)

print(a)
print(b)
print(c)

# 2x2 array using arange
arr = np.arange(4).reshape(2, 2)
print(arr)

# (a) Cube every element
print(arr ** 3)

# (b) Add 7 to every element
print(arr + 7)

# (c) Multiply every element by 2
print(arr * 2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[[0 1]
 [2 3]]
[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]
